# Generated by Django 5.0.2 on 2024-02-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Ifo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('is_married', models.BooleanField()),
                ('birthda', models.DateField()),
                ('birth_time', models.TimeField(auto_now_add=True)),
                ('bio', models.TextField(max_length=150)),
            ],
        ),
    ]
